- .github/workflows/ci.yml
- src/datatypes.rs
- src/handlers.rs
- src/main.rs
This patch adds extended query subprotocol support for our example.
Note that only a small amount of data types are supported. We will be adding more in future.
> feat: Extended query support

- src/datatypes.rs
- src/handlers.rs
According to the official wire protocol documentation[^1]:
> In simple Query mode, the format of retrieved values is always text, except when the given command is a FETCH from a cursor declared with the BINARY option.
However, for the binary protocol the situation is more complicated, as this is determined by the `Bind`[^3] command[^2]:
> Bind also specifies the format to use for any data returned by the query; the format can be specified overall, or per-column.
Given the above infromation, this aligns the implementation here with the `sqllite` and `duckdb` examples from the `pgwire` repository.
To see why the current state is an issue, try running `SELECT 1::int4` from a Rust crate that uses `rust-postgres`. Using the example from [this …
> handlers: fix response encoding format

- Cargo.lock
- datafusion-postgres/Cargo.toml
- datafusion-postgres/src/handlers.rs
I think every use of `SessionContext` can work with a reference.
> Remove Mutex around SessionContext

- datafusion-postgres/src/handlers.rs
This patch removes constraints from our handler for non-select statements. For example, there are still some other statement like explain, should be allowed for this tool.
> refactor: allow all types of statements

- datafusion-postgres/src/datatypes.rs
Avoid unwrapping `Result<RecordBatch>` because it can sometimes be an Err variant.  If so, instead of iterating over the records in the batch, iterator over a single error value, so the error will end up being handled by the calling code.
> Avoid unwrapping `Result<RecordBatch>`

- datafusion-postgres/src/handlers.rs
Until now, the parameter types were obtained by calling `.values()` on the HashSet of parameter types, but this leads to unpredicable ordering, causing queries to fail because their parameters were often transposed.
Instead, sort the parameter types by their names.  This should always work because in the postgresql case, the keys are '$1', '$2', etc.
> Fix parameter type ordering

- datafusion-postgres/src/datatypes.rs
Date32 is the number of seconds from the unix epoch, not from CE in the gregorian calendar.
> Fix mapping from NaiveDate to Date32

- datafusion-postgres/src/datatypes.rs
Hi @sunng87, thanks for this really useful project you created.
At the moment, Dictionary types are not supported in datafusion-postgres. 
But they're important since projects like delta-rs represent partition columns as Dictionary types. Specifically `Dictionary<UInt16, Utf8>` for Utf8 columns.
So running a query via datafusion-postgres would result in an error such as:
```rust
UserError(
ErrorInfo {
severity: "ERROR",
code: "XX000",
message: "Unsupported Datatype Dictionary(UInt16, Utf8) and array DictionaryArray {
keys: PrimitiveArray<UInt16>
[
0,
]
values: StringArray
[
\"test_project\",
]
}",
}
)
```
In the datafusion codebase: https://github.com/apache/datafusion/blob/main/datafusion/common/src/dfschema.rs#L665 
Dictionary types are treated as logically equal to their values: …
> Support Dictionary types as they're logically equivalent to their value types. Needed for delta-rs partition columns.

- datafusion-postgres/src/handlers.rs
For insert queries through Postgres text-based clients, the request goes through the SimpleQueryHandler. However, the SimpleQueryHandler does not return a valid response, causing such Postgres clients to crash. 
This PR catches insert queries and tries to return a valid response. E.g. `INSERT 0 1`
> Support "insert into" queries in SimpleQueryHandler

- Cargo.lock
- datafusion-postgres/Cargo.toml
- datafusion-postgres/src/datatypes.rs
Add support for `Decimal128` datatype
> Add support for Decimal128 datatype

- .gitignore
- flake.lock
- flake.nix
add nix flake environment setup. This is for my portable development environment. To use it, install `direnv` tool https://direnv.net/
> chore: introduce nix configuration

- Cargo.lock
- datafusion-postgres-cli/src/main.rs
- datafusion-postgres/Cargo.toml
- datafusion-postgres/src/lib.rs
This patch adds a shortcut function to start a server from `SessionContext`
> feat: high-level serve function for `SessionContext`

- README.md
- datafusion-postgres-cli/src/main.rs
- datafusion-postgres/src/handlers.rs
- datafusion-postgres/src/lib.rs
> refactor: accept arc reference for serve

- datafusion-postgres-cli/src/main.rs
- datafusion-postgres/src/lib.rs
- datafusion-postgres/src/pg_catalog.rs
- flake.lock
This patch reimplements pg_catalog using datafusion schema provider API.
In the first batch, I added empty pg_type table and a dynamic pg_class table.
> feat: add pg_catalog and its tables

- datafusion-postgres/src/pg_catalog.rs
Power BI tries to query this table when connecting a new data source
> feat: add empty pg_range table to pg_catalog

- datafusion-postgres/src/pg_catalog.rs
`MemTable` will use the length of input data vec as its available partition number. `MemTable::try_new` almost always accepts a 2d vec even if the data is empty
> fix: create MemTable with at least one partition

- datafusion-postgres/src/pg_catalog.rs
Fixes residual issues introduced in #112 
`\dt` from psql finally returns no error. I will debug it further to make it return correct results.
> fix: udf name and pg_is_table_visible

- datafusion-postgres/src/pg_catalog.rs
Implemented a stateful oid generator and cache to keep information in pg_catalog consistent. 
This patch makes `\dt` in psql works!
> feat: keep a cache of generated oids

- datafusion-postgres/src/handlers.rs
I ran into an issue where the entire global transaction state is marked as TransactionState::Failed, causing every other transaction to fail until the server is restarted, due to having a single transaction state for the entire application. 
When failing, all queries even from new connections return an error 
```sql
postgres=> select name,project_id,timestamp from otel_logs_and_spans where project_id='00000000-0000-0000-0000-000000000000' and date='2025-08-07' limit 30;
ERROR:  current transaction is aborted, commands ignored until end of transaction block
```
This PR refactors transaction state management to be per-connection (like postgres) instead of global:
- Per-connection isolation: Each connection now maintains its own transaction state using a HashMap<ConnectionId, …
> Per connection trasnaction tracking and cleanup

- datafusion-postgres/src/handlers.rs
- datafusion-postgres/src/lib.rs
- datafusion-postgres/src/sql.rs
Add this parser/rewriter to update sql that datafusion could not handle
> feat: add sql rewrite rules framework and alias rewrite rule

- datafusion-postgres/src/sql.rs
Postgres resolves identified after projection resolved, so it's possible to use unqualified identifier in order by or where clause, even if all tables are aliased. However, this is not supported by datafusion.
In this patch, we inference qualifier for those unqualified ids in order by and where, by checking any wildcard field in select projection. 
This is the very first step of implementing this rule.
> feat: add sql rewrite rule to resolve unqualified identifier

- datafusion-postgres/src/pg_catalog.rs
- datafusion-postgres/src/pg_catalog/catalog_info.rs
- datafusion-postgres/src/pg_catalog/pg_attribute.rs
- datafusion-postgres/src/pg_catalog/pg_class.rs
- datafusion-postgres/src/pg_catalog/pg_database.rs
- datafusion-postgres/src/pg_catalog/pg_namespace.rs
- datafusion-postgres/src/pg_catalog/pg_tables.rs
This patch adds a layer for abstraction for CatalogProviderList, so that if you are not using DataFusion's built-in catalog, you will still be able to generate `pg_catalog`.
> refactor: add a layer of abstraction for CatalogProviderList

- datafusion-postgres/src/pg_catalog.rs
- datafusion-postgres/src/pg_catalog/pg_stat_gssapi.rs
Implement the pg_stat_gssapi table, which will always contain a single
record showing only the current user.   Also, implement pg_backend_pid
function.
Both of these always use `BACKEND_PID` as the pid, which is currently hard coded to 1.
These additions help towards making pgadmin startup queries run.
> Implement pg_stat_gssapi & pg_backend_pid()

- Cargo.lock
- arrow-pg/Cargo.toml
- arrow-pg/examples/duckdb.rs
- flake.nix
https://github.com/sunng87/pgwire/pull/318
Moved from pgwire for better dependency management. Although having duckdb in this repo is a little weird...
> chore: add duckdb example to arrow-pg

- datafusion-postgres/src/handlers.rs
We already handle "rows affected" properly for do_query in the SimpleQueryHandler implementation, so let's do the same for do_query in the ExtendedQueryHandler implementation too.
To avoid duplicate code, this common logic has been extracted into a new `map_rows_affected_for_insert` function.
> Fix insert "rows affected" for extended queries

- datafusion-postgres/src/handlers.rs
Fixes #202 
This patch adds statement count check for parser so it will not crash on empty statement.
> fix: empty query check and mult-statement support
